language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install .
script:
  - python -m unittest discover -s test/skip

deploy:
  repository: https://pypi.python.org/pypi
  user: "nipdep"
  password: "W7gfK9uV"
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: main
    tag: true

